const products = [
  {
    id: 1,
    name: "Cable Management Kit (300 PCS)",
    nameAr: "طقم تنظيم الكابلات (300 قطعة)",
    slug: "cable-management-kit-300pcs",
    description: "Fast adhesive cable organizer - 300 pieces",
    descriptionAr: "منظم كابلات لاصق سريع - 300 قطعة",
    price: 65,
    category: "Workspace",
    featured: true,
    image: "📦",
    images: ["📦", "📦", "📦", "📦", "📦"],
    colors: "Black-Multi",
    colorsAr: "أسود، متعدد الألوان",
    packaging: "Each set separately (50 packages)",
    packagingAr: "كل مجموعة منفصلة (50 عبوة)",
    detailedDescription: "Professional 300-piece cable management solution with fast adhesive backing.",
    detailedDescriptionAr: "حل احترافي لإدارة الكابلات مكون من 300 قطعة مع ظهر لاصق سريع.",
    specifications: ["300 pieces total", "Fast adhesive backing"],
    specificationsAr: ["إجمالي 300 قطعة", "ظهر لاصق سريع"]
  },
  {
    id: 2,
    name: "Colorful Hook Loop Straps (15cm)",
    nameAr: "أشرطة حلقية ملونة (15 سم)",
    slug: "colorful-hook-loop-straps-15cm",
    description: "Reusable adjustable cable straps - 50 pieces",
    descriptionAr: "أشرطة كابلات قابلة لإعادة الاستخدام - 50 قطعة",
    price: 45,
    category: "Workspace",
    featured: false,
    image: "🎨",
    images: ["🎨"],
    colors: "Red, Blue, Green, Black, Yellow",
    colorsAr: "أحمر، أزرق، أخضر، أسود، أصفر",
    packaging: "Each pack contains 50 pieces",
    packagingAr: "كل عبوة تحتوي على 50 قطعة",
    detailedDescription: "Eco-friendly double-sided strong adhesive reusable straps.",
    detailedDescriptionAr: "أشرطة حلقية صديقة للبيئة ذات وجهين لاصقة قوية قابلة لإعادة الاستخدام.",
    specifications: ["Length: 15cm", "50 pieces total"],
    specificationsAr: ["الطول: 15 سم", "50 قطعة إجمالي"]
  },
  {
    id: 7,
    name: "Smart Plug",
    nameAr: "مقبس ذكي",
    slug: "smart-plug",
    description: "WiFi-enabled smart socket",
    descriptionAr: "مقبس ذكي بخاصية WiFi",
    price: 55,
    category: "Home",
    featured: true,
    image: "🔌",
    images: ["🔌"],
    colors: "White",
    colorsAr: "أبيض",
    detailedDescription: "WiFi-enabled smart plug for home automation.",
    detailedDescriptionAr: "مقبس ذكي بتقنية WiFi للتحكم المنزلي الذكي.",
    specifications: ["WiFi enabled"],
    specificationsAr: ["تقنية WiFi"]
  },
  {
    id: 11,
    name: "Phone Stand",
    nameAr: "حامل هاتف",
    slug: "phone-stand",
    description: "Adjustable phone stand",
    descriptionAr: "حامل هاتف قابل للتعديل",
    price: 35,
    category: "Phone Accessories",
    featured: false,
    image: "📱",
    images: ["📱"],
    colors: "Black",
    colorsAr: "أسود",
    detailedDescription: "Placeholder for your phone accessories.",
    detailedDescriptionAr: "مكان مخصص لإكسسوارات الهاتف الخاصة بك.",
    specifications: ["Adjustable"],
    specificationsAr: ["قابل للتعديل"]
  },
  {
    id: 12,
    name: "Car Charger",
    nameAr: "شاحن سيارة",
    slug: "car-charger",
    description: "Fast car charger",
    descriptionAr: "شاحن سيارة سريع",
    price: 40,
    category: "Car Accessories",
    featured: false,
    image: "🚗",
    images: ["🚗"],
    colors: "Silver",
    colorsAr: "فضي",
    detailedDescription: "Placeholder for your car accessories.",
    detailedDescriptionAr: "مكان مخصص لإكسسوارات السيارة الخاصة بك.",
    specifications: ["Fast charge"],
    specificationsAr: ["شحن سريع"]
  }
];

const categoryTranslations = {
  "All Products": "جميع المنتجات",
  "Workspace": "مساحة العمل",
  "Home": "المنزل",
  "Phone Accessories": "إكسسوارات الهاتف",
  "Car Accessories": "إكسسوارات السيارة"
};
