const products = [
  {
    id: 1,
    name: "Cable Management Kit (300 PCS)",
    nameAr: "طقم تنظيم الكابلات (300 قطعة)",
    slug: "cable-management-kit-300pcs",
    description: "Fast adhesive cable organizer - 300 pieces",
    descriptionAr: "منظم كابلات لاصق سريع - 300 قطعة",
    price: 65,
    category: "Workspace",
    featured: true,
    image: "📦",
    images: ["📦", "📦", "📦", "📦", "📦"],
    colors: "Black-Multi",
    colorsAr: "أسود، متعدد الألوان",
    packaging: "Each set separately (50 packages)",
    packagingAr: "كل مجموعة منفصلة (50 عبوة)",
    detailedDescription: "Professional 300-piece cable management solution with fast adhesive backing.",
    detailedDescriptionAr: "حل احترافي لإدارة الكابلات مكون من 300 قطعة مع ظهر لاصق سريع.",
    specifications: ["300 pieces total", "Fast adhesive backing"],
    specificationsAr: ["إجمالي 300 قطعة", "ظهر لاصق سريع"]
  },
  {
    id: 2,
    name: "Colorful Hook Loop Straps (15cm)",
    nameAr: "أشرطة حلقية ملونة (15 سم)",
    slug: "colorful-hook-loop-straps-15cm",
    description: "Reusable adjustable cable straps - 50 pieces",
    descriptionAr: "أشرطة كابلات قابلة لإعادة الاستخدام - 50 قطعة",
    price: 45,
    category: "Workspace",
    featured: false,
    image: "🎨",
    images: ["🎨"],
    colors: "Red, Blue, Green, Black, Yellow",
    colorsAr: "أحمر، أزرق، أخضر، أسود، أصفر",
    packaging: "Each pack contains 50 pieces",
    packagingAr: "كل عبوة تحتوي على 50 قطعة",
    detailedDescription: "Eco-friendly double-sided strong adhesive reusable straps.",
    detailedDescriptionAr: "أشرطة حلقية صديقة للبيئة ذات وجهين لاصقة قوية قابلة لإعادة الاستخدام.",
    specifications: ["Length: 15cm", "50 pieces total"],
    specificationsAr: ["الطول: 15 سم", "50 قطعة إجمالي"]
  },
  {
    id: 3,
    name: "Black Hook Loop Straps (15cm)",
    nameAr: "أشرطة حلقية سوداء (15 سم)",
    slug: "black-hook-loop-straps-15cm",
    description: "Professional black cable straps - 50 pieces",
    descriptionAr: "أشرطة كابلات سوداء احترافية - 50 قطعة",
    price: 42,
    category: "Workspace",
    featured: false,
    image: "⚫",
    images: ["⚫"],
    colors: "Black",
    colorsAr: "أسود",
    packaging: "Each pack contains 50 pieces",
    packagingAr: "كل عبوة تحتوي على 50 قطعة",
    detailedDescription: "Professional-grade black hook loop straps for a clean, uniform look.",
    detailedDescriptionAr: "أشرطة حلقية سوداء احترافية للحصول على مظهر نظيف وموحد.",
    specifications: ["Length: 15cm", "50 pieces (all black)"],
    specificationsAr: ["الطول: 15 سم", "50 قطعة سوداء"]
  },
  {
    id: 4,
    name: "Colorful Silicon Cable Straps",
    nameAr: "أشرطة سيليكون ملونة للكابلات",
    slug: "colorful-silicon-cable-straps",
    description: "Multi-color silicon organizers - 15 pieces",
    descriptionAr: "منظمات سيليكون متعددة الألوان - 15 قطعة",
    price: 38,
    category: "Workspace",
    featured: false,
    image: "🌈",
    images: ["🌈"],
    colors: "Black, White, Green, Blue, Gray",
    colorsAr: "أسود، أبيض، أخضر، أزرق، رمادي",
    packaging: "Each pack contains 15 pieces",
    packagingAr: "كل عبوة تحتوي على 15 قطعة",
    detailedDescription: "Flexible silicon cable straps in beautiful modern colors.",
    detailedDescriptionAr: "أشرطة كابلات سيليكون مرنة بألوان عصرية جميلة.",
    specifications: ["15 pieces total", "Premium silicon material"],
    specificationsAr: ["15 قطعة إجمالي", "مادة سيليكون فاخرة"]
  },
  {
    id: 5,
    name: "Black Silicon Cable Straps (15 Pack)",
    nameAr: "أشرطة سيليكون سوداء للكابلات (15 قطعة)",
    slug: "black-silicon-cable-straps-15pack",
    description: "Professional black silicon straps - 15 pieces",
    descriptionAr: "أشرطة سيليكون سوداء احترافية - 15 قطعة",
    price: 35,
    category: "Workspace",
    featured: false,
    image: "⬛",
    images: ["⬛"],
    colors: "Black",
    colorsAr: "أسود",
    packaging: "Each pack contains 15 pieces",
    packagingAr: "كل عبوة تحتوي على 15 قطعة",
    detailedDescription: "Premium black silicon cable straps for a minimalist aesthetic.",
    detailedDescriptionAr: "أشرطة كابلات سيليكون سوداء فاخرة لجمالية بسيطة.",
    specifications: ["15 pieces (all black)", "Premium silicon"],
    specificationsAr: ["15 قطعة سوداء", "سيليكون فاخر"]
  },
  {
    id: 6,
    name: "AuraFlex Smart LED Neon Strip",
    nameAr: "شريط نيون LED ذكي (أورا فليكس)",
    slug: "auraflex-smart-led-neon-strip",
    description: "Vibrant, flexible neon lighting for home and office",
    descriptionAr: "إضاءة نيون مرنة ونابضة بالحياة للمنزل والمكتب",
    price: 95,
    category: "LED Lights",
    featured: true,
    image: "✨",
    images: ["✨", "✨"],
    colors: "RGB Multi-color",
    colorsAr: "ألوان RGB متعددة",
    packaging: "1x 5M LED Strip, 1x Remote, 1x Power Adapter",
    packagingAr: "1x شريط 5 متر، 1x جهاز تحكم، 1x محول طاقة",
    detailedDescription: "Transform your space with the AuraFlex Smart LED Neon Strip. Featuring smooth, dot-free illumination and flexible design, it's perfect for gaming setups, home theaters, or accent lighting.",
    detailedDescriptionAr: "حول مساحتك مع شريط نيون LED ذكي أورا فليكس. يتميز بإضاءة ناعمة وخالية من النقاط وتصميم مرن، مثالي لإعدادات الألعاب أو المسارح المنزلية أو الإضاءة التجميلية.",
    specifications: ["5 Meters length", "App & Remote control", "Waterproof IP65"],
    specificationsAr: ["طول 5 أمتار", "تحكم عبر التطبيق والريموت", "مقاوم للماء IP65"]
  },
  {
    id: 7,
    name: "Smart Plug",
    nameAr: "مقبس ذكي",
    slug: "smart-plug",
    description: "WiFi-enabled smart socket",
    descriptionAr: "مقبس ذكي بخاصية WiFi",
    price: 55,
    category: "Home",
    featured: true,
    image: "🔌",
    images: ["🔌"],
    colors: "White",
    colorsAr: "أبيض",
    packaging: "Single unit",
    packagingAr: "وحدة واحدة",
    detailedDescription: "WiFi-enabled smart plug for home automation.",
    detailedDescriptionAr: "مقبس ذكي بتقنية WiFi للتحكم المنزلي الذكي.",
    specifications: ["WiFi enabled", "App control"],
    specificationsAr: ["تقنية WiFi", "تحكم عبر التطبيق"]
  },
  {
    id: 8,
    name: "USB Hub",
    nameAr: "موزع USB",
    slug: "usb-hub",
    description: "7-port USB 3.0 hub",
    descriptionAr: "موزع USB 3.0 بـ 7 منافذ",
    price: 75,
    category: "Workspace",
    featured: false,
    image: "🔗",
    images: ["🔗"],
    colors: "Black",
    colorsAr: "أسود",
    packaging: "Single unit",
    packagingAr: "وحدة واحدة",
    detailedDescription: "7-port USB 3.0 hub for connecting multiple devices.",
    detailedDescriptionAr: "موزع USB 3.0 بـ 7 منافذ لتوصيل أجهزة متعددة.",
    specifications: ["7 USB ports", "USB 3.0"],
    specificationsAr: ["7 منافذ USB", "USB 3.0"]
  },
  {
    id: 9,
    name: "Product 9",
    nameAr: "منتج 9",
    slug: "product-9",
    description: "Placeholder product 9",
    descriptionAr: "منتج تجريبي 9",
    price: 100,
    category: "Home",
    featured: false,
    image: "🎁",
    images: ["🎁"],
    colors: "Various",
    colorsAr: "متنوع",
    packaging: "Single unit",
    packagingAr: "وحدة واحدة",
    detailedDescription: "Placeholder product description.",
    detailedDescriptionAr: "وصف منتج تجريبي.",
    specifications: ["Feature 1", "Feature 2"],
    specificationsAr: ["ميزة 1", "ميزة 2"]
  },
  {
    id: 10,
    name: "Product 10",
    nameAr: "منتج 10",
    slug: "product-10",
    description: "Placeholder product 10",
    descriptionAr: "منتج تجريبي 10",
    price: 90,
    category: "Workspace",
    featured: false,
    image: "🎉",
    images: ["🎉"],
    colors: "Various",
    colorsAr: "متنوع",
    packaging: "Single unit",
    packagingAr: "وحدة واحدة",
    detailedDescription: "Placeholder product description.",
    detailedDescriptionAr: "وصف منتج تجريبي.",
    specifications: ["Feature 1", "Feature 2"],
    specificationsAr: ["ميزة 1", "ميزة 2"]
  }
];

const categoryTranslations = {
  "All Products": "جميع المنتجات",
  "Workspace": "مساحة العمل",
  "Home": "المنزل",
  "Phone Accessories": "إكسسوارات الهاتف",
  "Car Accessories": "إكسسوارات السيارة",
  "LED Lights": "إضاءة LED"
};
